@startuml
'https://plantuml.com/class-diagram

interface Multiset {

+bool add(item: Any)
+None remove(item: Any)
+bool contains(item: Any)
+bool is_empty()
+int count(item: Any)
+int size()

}

class Tree {
-_root: Any
-_subtrees: List[Tree]

+bool is_empty()
+int __len__()
+int count(item: Any)
+bool delete_item(item: Any)
+None _delete_root()
+None insert(item: Any)
+bool insert_child(item: Any, parent: Any)
+bool __eq__(other: Tree)
+bool __contains__(item: Any)
}

class TreeMultiSet {
-_tree: Tree

+bool add(item: Any)
+None remove(item: Any)
+bool contains(item: Any)
+bool is_empty()
+int count(item: Any)
+int size()
}

class ArrayListMultiset{
-_list: list

+bool add(item: Any)
+None remove(item: Any)
+bool contains(item: Any)
+bool is_empty()
+int count(item: Any)
+int size()
}

class LinkedListMultiSet {
-_front: _Node | None
-_size: int

+bool add(item: Any)
+None remove(item: Any)
+bool contains(item: Any)
+bool is_empty()
+int count(item: Any)
+int size()

}

class _Node {
+item: Any
+next: _Node | None

}


Multiset <|-- TreeMultiSet
Multiset <|-- ArrayListMultiset
Multiset <|-- LinkedListMultiSet
_Node *-- LinkedListMultiSet
Tree *-- TreeMultiSet


@enduml
